### ISSUE TITLE
ImportError: cannot import name 'cdmapi' from 'pywidevine.cdm'

### ISSUE THREAD

**Issue by Palyer321** [T3rry7f/NoDRM#21]
When trying PywidevineX the following error occured!

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pywidevine.decrypt.wvdecrypt import WvDecrypt
  File "/root/NoDRM/PywidevineX/pywidevine/decrypt/wvdecrypt.py", line 6, in <module>
    from pywidevine.cdm import cdm, deviceconfig
  File "/root/NoDRM/PywidevineX/pywidevine/cdm/cdm.py", line 22, in <module>
    from pywidevine.cdm import cdmapi
ImportError: cannot import name 'cdmapi' from 'pywidevine.cdm' (/root/NoDRM/PywidevineX/pywidevine/cdm/__init__.py)
```

I was running this on Ubuntu 20.04 (LTS) x64 !

Please can anyone help me to resolve this issue! It would be really helpful for me because I am a kind of a beginner and was finding a way to make this work on linux/ubuntu from the beginning. Thank you sir @T3rry7f for this amazing work!

**Comment by GhostXRJ** [comment]
@Palyer321 make a small script, you may need the xml parser (element tree api) to extract the pssh

**Comment by chef112** [comment]
> @Palyer321 make a small script, you may need the xml parser (element tree api) to extract the pssh

yes make php parseer to extract pssh and send over osm/api  ,, works very well

**Comment by VCDEV1** [comment]
Thank you. I will try @GhostXRJ @chef112
